version: "3"
services:

  gui:
    build: ./irengine-gui
    ports:
      - ${LISTEN_ADDRESS}:8080:80
    restart: $RESTART

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=${ELASTICSEARCH_CORS}
      - http.cors.allow-origin=${ELASTICSEARCH_CORS_ALLOW_ORIGIN}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./irconfig/synonym/wn_s.pl:/usr/share/elasticsearch/config/wn_s.pl
    ports:
      - ${LISTEN_ADDRESS}:9200:9200
    restart: $RESTART

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - ${LISTEN_ADDRESS}:5601:5601
    restart: $RESTART

  irengine:
    build: ./irengine
    depends_on:
      - elasticsearch
    volumes:
      - ./irconfig:/usr/src/app/irconfig
    restart: "no"

volumes:
  elasticsearch-data:
