elasticsearch_hosts: []
elasticsearch_indices:
  users:
    name: users
    body: >-
      {
        "settings": {
        },
        "mappings": {
          "properties": {
          }
        }
      }
  usertweets:
    name: usertweets
    file: mappings/tweets.json
users:
  - name: BarackObama
    count: 10
  - name: BorisJohnson
    count: 10
  - name: JoeBiden
    count: 10
  - name: KingJames
    count: 10
  - name: sterling7
    count: 10
  - name: KDTrey5
    count: 10