elasticsearch_hosts: []
elasticsearch_indices:
  users:
    name: users
    body: >-
      {
        "settings": {
        },
        "mappings": {
          "properties": {
          }
        }
      }
  usertweets:
    name: usertweets
    file: mappings/tweets.json

  retrievalbase:
    name: retrievalbase
    file: mappings/tweets.json

users:
  - name: BarackObama
    count: 100
  - name: BorisJohnson
    count: 100
  - name: JoeBiden
    count: 100
  - name: KingJames
    count: 100
  - name: sterling7
    count: 100
  - name: KDTrey5
    count: 100

retrievalbase:
  - name: WSJ
    count: 100
  - name: BBCWorld
    count: 100
  - name: nytimes
    count: 100
  - name: USATODAY
    count: 100