elasticsearch_hosts: []
elasticsearch_indices:
  user:
    name: user
    body: >-
      {
        "settings": {
        },
        "mappings": {
          "properties": {
          }
        }
      }
  usertweets:
    name: usertweets
    body: >-
      {
        "settings": {
        },
        "mappings": {
          "properties": {
          }
        }
      }
users:
  - name: BarackObama
    count: 5
  - name: BorisJohnson
    count: 5
  - name: JoeBiden
    count: 5
  - name: KingJames
    count: 5
  - name: sterling7
    count: 5
  - name: KDTrey5
    count: 5